# Generated by Django 5.2.12 on 2026-03-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_update_blogpost_excerpt_and_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
    ]
